-- MySQL Script generated by MySQL Workbench
-- 06/26/16 17:42:56
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema system
-- -----------------------------------------------------
-- 一个通用的Java快速开发框架项目数据库基础表
CREATE SCHEMA IF NOT EXISTS `system` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `system` ;

-- -----------------------------------------------------
-- Table `system`.`TSYS_MENU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system`.`TSYS_MENU` (
  `id` VARCHAR(60) NOT NULL COMMENT '主键',
  `pid` VARCHAR(60) NULL COMMENT '父菜单id',
  `menu_code` VARCHAR(45) NULL COMMENT '菜单编码',
  `menu_name` VARCHAR(60) NULL COMMENT '菜单名',
  `menu_url` VARCHAR(100) NULL COMMENT '菜单url',
  `is_leaf` TINYINT NULL COMMENT '是否是叶子节点',
  `description` VARCHAR(100) NULL COMMENT '菜单描述',
  `remark` VARCHAR(100) NULL COMMENT '备注',
  `menu_level` TINYINT NULL COMMENT '菜单等级：1、一级菜单；2、二级菜单；3、三级菜单；',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system`.`TSYS_ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system`.`TSYS_ROLE` (
  `id` VARCHAR(50) NOT NULL COMMENT '主键',
  `role_code` VARCHAR(50) NULL COMMENT '角色编码',
  `role_name` VARCHAR(50) NULL COMMENT '角色名',
  `description` VARCHAR(100) NULL COMMENT '角色描述',
  `remark` VARCHAR(100) NULL COMMENT '备注',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system`.`TSYS_ROLE_MENU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system`.`TSYS_ROLE_MENU` (
  `id` VARCHAR(60) NOT NULL COMMENT '主键',
  `role_id` VARCHAR(60) NULL COMMENT '角色id',
  `menu_id` VARCHAR(60) NULL COMMENT '菜单id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system`.`TSYS_USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system`.`TSYS_USER` (
  `id` VARCHAR(60) NOT NULL,
  `user_login_name` VARCHAR(100) NULL COMMENT '用户登陆名',
  `user_name` VARCHAR(100) NULL COMMENT '用户名',
  `password` VARCHAR(200) NULL COMMENT '密码',
  `state` TINYINT NULL COMMENT '用户状态',
  `organ_code` VARCHAR(100) NULL COMMENT '用户所属机构',
  `organ_name` VARCHAR(100) NULL,
  `login_error_count` TINYINT NULL COMMENT '登陆错误次数',
  `auto_unlock_time` TIMESTAMP NULL COMMENT '自动解锁时间',
  `create_time` TIMESTAMP NULL COMMENT '账号创建时间',
  `last_login_time` TIMESTAMP NULL COMMENT '最近一次登录时间',
  `last_pwd_modify_time` DATETIME NULL COMMENT '最近一次密码修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system`.`TSYS_USER_ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system`.`TSYS_USER_ROLE` (
  `id` VARCHAR(60) NOT NULL COMMENT '主键',
  `user_id` VARCHAR(60) NULL COMMENT '用户id',
  `role_id` VARCHAR(60) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system`.`tdic_key`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system`.`tdic_key` (
  `id` VARCHAR(50) NOT NULL COMMENT '主键',
  `key_name` VARCHAR(100) NULL COMMENT '键名字',
  `key_code` VARCHAR(100) NULL COMMENT '键的编码',
  `remark` VARCHAR(100) NULL COMMENT '备注',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system`.`tdic_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system`.`tdic_value` (
  `id` VARCHAR(50) NOT NULL COMMENT '主键',
  `key_code` VARCHAR(100) NULL COMMENT '键的编码',
  `value_code` VARCHAR(100) NULL,
  `value_name` VARCHAR(100) NULL COMMENT '值的名字',
  `sort` TINYINT NULL COMMENT '值的排序',
  `remark` VARCHAR(100) NULL COMMENT '备注',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system`.`tsys_organ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system`.`tsys_organ` (
  `id` VARCHAR(60) NOT NULL COMMENT '主键',
  `pid` VARCHAR(60) NULL,
  `organ_code` VARCHAR(45) NULL COMMENT '机构编码',
  `organ_name` VARCHAR(45) NULL COMMENT '机构名',
  `sort` TINYINT NULL COMMENT '在当前父菜单下的排序位置',
  `description` VARCHAR(100) NULL COMMENT '描述',
  `remark` VARCHAR(100) NULL,
  `organ_level` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system`.`tsys_param`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system`.`tsys_param` (
  `id` VARCHAR(60) NOT NULL,
  `param_code` VARCHAR(45) NULL COMMENT '参数编码',
  `param_name` VARCHAR(45) NULL COMMENT '参数名',
  `param_value` VARCHAR(45) NULL COMMENT '参数值',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `modify_time` DATETIME NULL COMMENT '修改时间',
  `remark` VARCHAR(100) NULL COMMENT '备注',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system`.`tsys_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system`.`tsys_log` (
  `id` VARCHAR(50) NOT NULL,
  `subject` VARCHAR(45) NULL COMMENT '日志主题',
  `content` VARCHAR(300) NULL COMMENT '日志内容',
  `operator` VARCHAR(45) NULL COMMENT '操作人',
  `create_time` DATETIME NULL COMMENT '时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
